# This is a list of mods that will be downloaded without the client giving explicit permission.
# In the future, this may be moved to an external server
# To add a new mod to the list, please follow the format: modrinth-slug = "modrinth-project-id"
[Whitelist]
  adorn = "E6FUtRJh"
  advancedfurnace = "e3RoZUwe"
  advancementinfo = "G1epq3jN"
  ae2 = "XxWD5pD3"
  aether = "IKpsG0nF"
  afkpeace = "65jTHvHz"
  alternate-current = "r0v8vy1s"
  animatica = "PRN43VSY"
  antighost = "Jw3Wx1KR"
  appleskin = "EsAfCjCV"
  autoswitch = "uSdcnlts"
  axes-are-weapons = "1jvt7RTc"
  bedrockIfy = "ox3rDp1B"
  beenfo = "Bta0Pt47"
  better-beds = "kKwy3HU9"
  betterf3 = "8shC1gFX"
  blur-fabric = "NK39zBp2"
  boat-item-view = "BdKIyOLe"
  bobby = "M08ruV16"
  brb = "vWIaVOTE"
  campanion = "Y2Rds0HS"
  charm = "pOQTcQmj"
  charmonium = "bpii4Xsa"
  chime = "ubxU84eR"
  chunky = "fALzjamp"
  cinderscapes = "QC4wcUXZ"
  cit-resewn = "otVJckYQ"
  cleardespawn = "yoJJjRRE"
  clickthrough = "Z5b0cAlD"
  colored-lights = "oDZufc9Z"
  consistencyplus = "nDHcEOt3"
  continuity = "1IjD5062"
  cull-leaves = "GNxdLCoP"
  dashloader = "ZfQ3kTvR"
  dcch = "sUbMm93i"
  deathlog = "TPAYeAOc"
  detail-armor-bar = "hAt6ty93"
  dont-drop-it = "HcVOCzMh"
  dripsounds-fabric = "T8MMXTpr"
  durabilityviewer = "LTM1f0yY"
  dynamic-fps = "LQ3K71Q1"
  dynamicsurroundingsfabric = "H7fshfpD"
  easierchests = "1aloFY8o"
  easiercrafting = "UylF21yz"
  easiervillagertrading = "ChscgScW"
  eating-animation = "rUgZvGzi"
  ebe = "OVuFYfre"
  editsign = "hFMCvH85"
  enhanced-attack-indicator = "eTy17BBS"
  entity-distance = "msRGy0cC"
  extrasounds = "uPWCQrVL"
  fabric-api = "P7dR8mSH"
  fabric-language-kotlin = "Ha28R6CL"
  fabricskyboxes = "YBz7DOs8"
  fabrictailor = "g8w1NapE"
  fabrishot = "3qsfQtE9"
  fabulousclouds = "Dx7R69WU"
  fade-in-chunks = "uWSgLtUe"
  fallingleaves = "WhbRG4iK"
  fallingtree = "Fb4jn8m6"
  ferrite-core = "uXXizFIs"
  figura = "B3csO4KD"
  fpsdisplay = "DIlqwRFH"
  fvt = "TjrP0eTG"
  gamma-utils = "wdLuzzEP"
  heads-down-display = "f02hMbGH"
  healthcare = "NNqujQWr"
  horsestatsvanilla = "l4qoXLzx"
  hydrogen = "AZomiSrC"
  icommon = "SVKv1SZo"
  illuminations = "6EFgqQWR"
  immersivecursedness = "lyiXgXNm"
  immersiveportals = "zJpHMkdD"
  indium = "Orvt0mRa"
  infernal-expansion = "ZrpxHZN4"
  infinitevillagertrading = "FDXO8hkq"
  inspecio = "a93H3mKU"
  inventory-profiles-next = "O7RBXm3n"
  invmove-fabric = "McNdqLv2"
  invsync = "F4ANsPlF"
  invview = "jrDKjZP7"
  iris = "YL57xq9U"
  isometric-renders = "M0aimenU"
  lambdabettergrass = "2Uev7LdA"
  lambdacontrols = "W1D3UXEc"
  lambdynamiclights = "yBW8D80W"
  lazydfu = "hvFnDODi"
  ledger = "LVN9ygNV"
  level-border = "zyAuOrGS"
  limitless = "Qx0jUYY8"
  lithium = "gvQqBUqZ"
  mcdiscordchat = "D0sHdnXY"
  mo-structures = "PTGd6dWp"
  modmanager = "6kq7BzRK"
  modmenu = "mOgUt4GM"
  mouse-wheelie = "u5Ic2U1u"
  no-strip = "3f1BdVqy"
  no-telemetry = "hg77g4Pw"
  notenoughcrashes = "yM94ont6"
  ok-zoomer = "aXf2OSFU"
  origins = "3BeIrqZR"
  ost-overhaul = "M11EPNE5"
  pehkui = "t5W7Jfwy"
  perfect-accuracy = "ochFsQSn"
  petowner = "IxUlAAFe"
  phosphor = "hEOCdOgW"
  pinglist = "GzmTgzUV"
  plasmo-voice = "1bZhdhsH"
  presence-footsteps = "rcTfTZr3"
  rainbowify = "m9FFV06N"
  reeses-sodium-options = "Bh37bMuy"
  repurposed-structures-fabric = "muf0XoRe"
  requiem = "bYmqMxlQ"
  respackopts = "TiF5QWZY"
  rpmtw-update-mod = "ZukQzaRP"
  seamless-loading-screen = "TyTPFOiF"
  seedmapper = "C4GbEnuY"
  servercore = "4WWQxlQP"
  sit = "eM1KzRjc"
  skyblocker = "PdxhF16M"
  smooth-swapping = "ydZic5r4"
  smoothboot-fabric = "FWumhS4T"
  sodium = "AANobbMI"
  sodium-extra = "PtjYWJkn"
  soundphysics = "Af0DueBa"
  starlight = "H8CaAYZC"
  stendhal = "BWloQ9jK"
  stepup = "AnNXBWLE"
  stoneholm = "zQoJfY3W"
  styled-chat = "doqSKB0e"
  styledplayerlist = "DQIfKUHf"
  tabtps = "cUhi3iB2"
  terra = "FIlZB9L0"
  terrestria = "lsUDPMOT"
  traverse = "kXygSBVI"
  universal-graves = "yn9u3ypm"
  visual-overhaul = "YQnwl5Vv"
  visuality = "rI0hvYcd"
  vtdownloader = "1E2sq1cp"
  worldtime = "uCcYS9la"
  wthit = "6AQIaxuO"